version: '3'

networks:
  nginx-proxy:
    name: nginx-proxy
    external: true

services:
  astro-rescue:
    container_name: astro-rescue
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=dev.rescuesneaks.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=dev.rescuesneaks.com
      - LETSENCRYPT_EMAIL=jcanahuirev@gmail.com
    networks:
      - nginx-proxy